M48
; DRILL file {KiCad (6.0.2)} date Mon May 16 11:26:36 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-16T11:26:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X2.25Y30.0
X2.25Y8.0
X19.75Y30.0
X19.75Y8.0
T2
X3.0Y35.0
X3.0Y3.0
T0
M30
